name: ML Pipeline

on:
  push:
    paths:
      - '05_Building_First_Neural_Networks_and_MLOps_Basics/**'
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 05_Building_First_Neural_Networks_and_MLOps_Basics

    steps:
    - uses: actions/checkout@v2
    
    - name: Debug Information
      run: |
        echo "GitHub ref: ${{ github.ref }}"
        echo "Current directory: $PWD"
        ls -la
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Train model
      run: |
        python train.py
        
    - name: Run tests
      run: |
        pytest test_model.py -v
        
    - name: Upload trained model
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: 05_Building_First_Neural_Networks_and_MLOps_Basics/model_weights_*.pth