name: CNN Pipeline

on:
  push:
    paths:
      - '06_CNNs_its_Components_and_Back_Propagation/**'
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 06_CNNs_its_Components_and_Back_Propagation

    steps:
    - uses: actions/checkout@v4
    
    - name: Debug Information
      run: |
        echo "GitHub ref: ${{ github.ref }}"
        echo "Current directory: $PWD"
        ls -la
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Train model
      run: |
        python train.py
        
    - name: Run tests
      run: |
        pytest test_model.py -v 